# Generated by Django 3.1 on 2020-08-16 01:13

import conversions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inputfile', models.FileField(upload_to=conversions.models.file_directory_path)),
                ('convertedfile', models.FileField(upload_to='converted/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
